'use strict';
import { accountApi, renderAuth } from './account-ui.js';
import { renderRolePanel } from './roles-ui.js';
import { renderTickets, renderTransfer, renderHistory } from './tickets-ui.js';
import { renderLegal, legalSummary, LEGAL } from './legal.js';
import { stopScanner } from './scanner-ui.js';
let currentUser = null;
async function useAccount(account) {
  orders=[];currentUser=account;signed=Boolean(account);user=account?.name||'';
  if(signed){orders=(await accountApi('orders',null,'GET')).orders;noticeExpired(await syncHold())}
  else{holdSeq++;applyHold(null)}
}
async function logout() {
  try {
    await accountApi('auth/logout');await useAccount(null);
    selected=[];quantity=1;paid=false;authNext='';
    sessionStorage.removeItem('eticket-verification');go('inicio');toast('Sesión cerrada.');
  } catch(err) {toast(err.message);}
}
const $=s=>document.querySelector(s), app=$('#app');
let events=[
{id:1,name:'Ecos de medianoche',artist:'Sesión en vivo',category:'Conciertos',city:'Mérida',date:'2026-11-14',hour:'20:00',venue:'Teatro del Centro',base:450,zone:'Preferente',type:'seat',class:'p1',tag:'EN VIVO',desc:'Una noche de música alternativa en un formato íntimo. Disfruta el concierto con asiento numerado y elige tu lugar antes de confirmar.'},
{id:2,name:'Entre dos mundos',artist:'Compañía Horizonte',category:'Teatro',city:'Mérida',date:'2026-11-21',hour:'19:30',venue:'Foro Horizonte',base:280,zone:'Luneta',type:'seat',class:'p2',tag:'EN ESCENA',desc:'Una obra sobre los encuentros que cambian nuestra forma de ver el mundo. Una función para disfrutar de cerca, con localidades numeradas.'},
{id:3,name:'Ritmo al aire libre',artist:'Festival de otoño',category:'Festivales',city:'Cancún',date:'2026-12-05',hour:'17:00',venue:'Parque del Mar',base:650,zone:'General',type:'general',class:'p3',tag:'FESTIVAL',desc:'Una tarde de música y nuevas conexiones. Acceso a zona general de pie, sin asiento asignado. Selecciona hasta seis entradas por compra.'},
{id:4,name:'Noche de comedia',artist:'Risas en el foro',category:'Comedia',city:'Mérida',date:'2026-11-28',hour:'21:00',venue:'Foro Norte',base:320,zone:'General',type:'general',class:'p4',tag:'COMEDIA',desc:'Una noche de historias y humor. Entrada general sin asiento numerado; el acceso a la zona está sujeto al aforo disponible.'},
{id:5,name:'Piano en penumbra',artist:'Recital de temporada',category:'Conciertos',city:'Campeche',date:'2026-12-12',hour:'20:00',venue:'Sala del Centro',base:390,zone:'Preferente',type:'seat',class:'p5',tag:'RECITAL',desc:'Un recital de piano en una sala de aforo reducido. Elige una localidad numerada y disfruta cada interpretación.'}
];
// T10.6: the service fee comes from the server; T11.8: sold-out status per event and function.
let feeRate=0.10,availability={};
const price=e=>Math.round(e.base*(1+feeRate)*1.16*100)/100;
const soldOutLabel=e=>{const a=availability[String(e.id)];return a?(a.soldOut?'<span class="pill bad">Agotado</span>':'<span class="pill ok">En venta</span>'):''};
const money=n=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN'}).format(n);
const date=s=>new Date(s+'T12:00:00').toLocaleDateString('es-MX',{day:'numeric',month:'long',year:'numeric'});
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function save(key,v){try{localStorage.setItem(key,JSON.stringify(v))}catch{toast('No se pudo guardar en este navegador. Conserva la página abierta.')}}
let signed=false, user='', activeEvent=1, selected=[], quantity=1, hold=null, paid=false, filter={q:'',cat:'',date:'',city:'',price:''}, orders=[];
let detailEventId='',activeFunctionIndex=0,activeZoneName='',selectedFunction=null;
let authNext='', paymentError='', forceError='', warning=false;
let holdClock={at:0,left:0}, holdSeq=0, holdBusy=false, expiring=false, editingHold='', seatPoll=0, liveSeats=null, barKey='';
const holdChannel=typeof BroadcastChannel==='function'?new BroadcastChannel('eticket-hold'):null;
const purchaseRoutes=['localidades','resumen','pago','procesando','cancelar','en-curso'];
const evt=()=>events.find(e=>e.id===activeEvent)||events[0];
const count=()=>evt().type==='seat'?selected.length:quantity;
// The hold comes from the server; between syncs the clock counts down with performance.now(), so the device clock never matters.
const holdLeft=()=>hold?Math.max(0,holdClock.left-(performance.now()-holdClock.at)):0;
const clockText=ms=>{const s=Math.ceil(ms/1000);return `${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`};
const routeName=()=>location.hash.slice(1).split('/')[0]||'inicio';
function applyHold(next){const changed=hold?.id!==next?.id;hold=next&&['active','paying'].includes(next.status)?next:null;if(hold)holdClock={at:performance.now(),left:hold.remainingMs};if(changed){warning=false;expiring=false;editingHold=''}}
function setHold(next){holdSeq++;applyHold(next);holdChannel?.postMessage('sync');tick()}
async function syncHold(background=false){if(!signed){applyHold(null);return null}const seq=++holdSeq,before=hold;let result;try{result=await accountApi('holds/current',null,'GET',background)}catch{return null}if(seq!==holdSeq)return null;const shape=h=>h?`${h.id}|${h.status}|${h.seats.join()}|${h.quantity}`:'',changed=shape(before)!==shape(result.hold);applyHold(result.hold);if(before&&!hold)holdClosed(result.recent?.id===before.id?result.recent.status:'',before);else if(changed&&['resumen','pago','procesando','en-curso'].includes(routeName()))render();tick();return result}
async function holdClosed(status,before){const inPurchase=purchaseRoutes.includes(routeName());if(status==='expired'){rememberExpired(before);paid=false;go('expirado');return}if(status==='completed'){try{orders=(await accountApi('orders',null,'GET')).orders}catch{}toast('Tu compra se completó. Consulta tus boletos.');if(inPurchase)go('boletos');return}toast(status==='cancelled'?'La compra se canceló y los lugares se liberaron.':'Tu compra en curso ya no está activa.');if(inPurchase)go('cartelera')}
function noticeExpired(result){const recent=result?.recent;if(result?.hold||recent?.status!=='expired'||result.now-recent.closed>3600000)return;try{if(localStorage.getItem('eticket-expired-notice')===recent.id)return;localStorage.setItem('eticket-expired-notice',recent.id)}catch{}toast('Tu compra anterior expiró: los lugares se liberaron y no se hizo ningún cobro.')}
function alignToHold(){if(!hold)return;const e=events.find(x=>String(x.id)===String(hold.eventId));if(!e)return;const fns=e.functions?.length?e.functions:[{id:'1'}];activeEvent=e.id;detailEventId=String(e.id);activeFunctionIndex=Math.max(0,fns.findIndex(fn=>String(fn.id??'1')===String(hold.functionId)));activeZoneName=hold.zone;configureEvent(e);if(hold.kind==='seat')selected=[...hold.seats];else quantity=hold.quantity}
function handleHoldError(err){if(err.status===410){rememberExpired(hold);paid=false;setHold(null);go('expirado');return}toast(err.message);syncHold().then(()=>render())}
function toast(s){$('#toast').textContent=s;$('#toast').classList.add('show');clearTimeout(window.toastTimeout);window.toastTimeout=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
function go(route){if(location.hash==='#'+route)render();else location.hash=route}
function back(fallback='cartelera'){return `<a class="back" href="#${fallback}">‹ Volver</a>`}
function poster(e,extra=''){const style=/^p[1-5]$/.test(e.class)?e.class:'p1';return `<div class="poster ${style} ${extra}" role="img" aria-label="Póster de ${esc(e.name)}"><span class="poster-no">eTicket PRESENTA · ${esc(e.tag)}</span><strong>${esc(e.name)}</strong><small>${date(e.date)} · ${esc(e.city)}<br>${esc(e.artist)}</small></div>`}
function card(e){return `<a class="card" href="#evento/${encodeURIComponent(e.id)}">${poster(e)}<div class="card-body"><span class="badge">${esc(e.category)}</span> ${soldOutLabel(e)}<h3>${esc(e.name)}</h3><p>${date(e.date)} · ${esc(e.hour)} h<br>${esc(e.venue)}, ${esc(e.city)}</p><div class="price"><div><strong>${money(price(e))}</strong><small>Por boleto · Cargo e IVA incluidos</small></div><span class="btn small">Ver evento</span></div></div></a>`}
function steps(n){return `<div class="progress" aria-label="Pasos de compra">${['Localidades','Resumen','Pago','Confirmación'].map((s,i)=>`<span class="${i===n?'active':''}" ${i===n?'aria-current="step"':''}>${i+1}. ${s}</span>`).join('')}</div>`}
function home(){app.innerHTML=`<section class="hero"><div><div class="eyebrow">Conecta con lo que te mueve</div><h1>Hay momentos<br>que se viven<br><em>en primera fila.</em></h1><p>Música, teatro y nuevas experiencias. Encuentra tu próximo evento y elige tu lugar.</p><a class="btn" href="#cartelera">Explorar cartelera</a></div><a href="#evento/1" aria-label="Ver Ecos de medianoche">${poster(events[0])}</a></section><div class="section-head"><h2>En el radar</h2><a href="#cartelera">Ver todos los eventos</a></div><div class="cards">${events.slice(0,3).map(card).join('')}</div>`}
function catalog(){app.innerHTML=`${back('inicio')}<div class="eyebrow">Encuentra tu próximo plan</div><h1>Cartelera</h1><form id="filters" class="filters"><div><label for="search">Buscar evento</label><input id="search" name="q" placeholder="Nombre del evento o artista" value="${esc(filter.q)}"></div><div><label for="category">Categoría</label><select id="category" name="cat"><option value="">Todas</option>${['Conciertos','Teatro','Festivales','Comedia'].map(x=>`<option ${filter.cat===x?'selected':''}>${x}</option>`).join('')}</select></div><div><label for="date">Fecha exacta</label><input id="date" type="date" name="date" value="${filter.date}"></div><div><label for="city">Ciudad</label><select id="city" name="city"><option value="">Todas</option>${['Mérida','Cancún','Campeche'].map(x=>`<option ${filter.city===x?'selected':''}>${x}</option>`).join('')}</select></div><div><label for="price">Precio total</label><select id="price" name="price"><option value="">Cualquier precio</option><option value="400" ${filter.price==='400'?'selected':''}>Hasta $400</option><option value="600" ${filter.price==='600'?'selected':''}>Hasta $600</option><option value="900" ${filter.price==='900'?'selected':''}>Hasta $900</option></select></div></form><div class="section-head" style="margin-top:20px"><span id="results" role="status"></span><button class="btn secondary small" id="clear">Limpiar filtros</button></div><div id="event-results" class="cards"></div>`;function update(){const list=events.filter(e=>(e.name+' '+e.artist).toLowerCase().includes(filter.q.toLowerCase())&&(!filter.cat||e.category===filter.cat)&&(!filter.date||e.date===filter.date)&&(!filter.city||e.city===filter.city)&&(!filter.price||price(e)<=Number(filter.price)));$('#results').textContent=list.length+' eventos disponibles';$('#event-results').className=list.length?'cards':'';$('#event-results').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h2>No encontramos eventos</h2><p>Prueba otra fecha, ciudad o categoría, o amplía el precio máximo.</p><button class="btn secondary" id="reset-empty">Quitar filtros</button></div>`;$('#reset-empty')?.addEventListener('click',reset)}function reset(){filter={q:'',cat:'',date:'',city:'',price:''};catalog()}$('#filters').addEventListener('input',()=>{filter=Object.fromEntries(new FormData($('#filters')));update()});$('#filters').onsubmit=e=>e.preventDefault();$('#clear').onclick=reset;update()}
function configureEvent(e){const fn=e.functions?.[activeFunctionIndex];selectedFunction=fn||null;if(fn){e.date=fn.date;e.hour=fn.hour}const zone=e.zones?.find(z=>z.name===activeZoneName)||e.zones?.[0];if(zone){activeZoneName=zone.name;e.base=Number(zone.price)||0;e.zone=zone.name;e.type=zone.type||(/general/i.test(zone.name)?'general':'seat');zone.totalCapacity=Number(zone.totalCapacity??zone.capacity)||0;e.zoneSold=Number(zone.salesByFunction?.[String(fn?.id||'1')])||0;zone.capacity=Math.max(0,zone.totalCapacity-e.zoneSold);e.capacity=zone.capacity;e.occupiedSeatIds=zone.occupiedByFunction?.[String(fn?.id||'1')]||[];zone.sold=0;zone.occupiedSeats=e.occupiedSeatIds;e.seatIds=zone.seats||[];e.accessibleSeats=zone.accessible||[]}return e}
function detail(id){let e=events.find(x=>String(x.id)===String(id));if(!e){missing();return}if(detailEventId!==String(id)){detailEventId=String(id);activeFunctionIndex=0;activeZoneName=''}configureEvent(e);const functions=e.functions?.length?e.functions:[{date:e.date,hour:e.hour}],zones=e.zones?.length?e.zones:[{name:e.zone,price:e.base,capacity:e.capacity||24,type:e.type}];app.innerHTML=`${back()}<div class="split"><div>${poster(e,'detail-poster')}<span class="badge">${esc(e.category)}</span><h1 style="font-size:38px;margin-top:15px">${esc(e.name)}</h1><p>${esc(e.desc)}</p><h2>Antes de asistir</h2><p>Apertura de puertas: una hora antes de la función. Conserva tu boleto y llega con tiempo.</p></div><aside class="panel"><div class="eyebrow">Tu próxima experiencia</div><h2>Elige función y zona</h2><label for="function">Función</label><select id="function">${functions.map((fn,i)=>`<option value="${i}" ${i===activeFunctionIndex?'selected':''}>${date(fn.date)} · ${esc(fn.hour)} h</option>`).join('')}</select><label for="zone-choice">Zona</label><select id="zone-choice">${zones.map(z=>`<option value="${esc(z.name)}" ${z.name===activeZoneName?'selected':''}>${esc(z.name)} · ${money(z.price)}</option>`).join('')}</select><dl class="info-list"><div><dt>Recinto</dt><dd>${esc(e.venue)} · ${esc(e.city)}</dd></div><div><dt>Precio final por boleto</dt><dd style="font-size:30px;color:var(--light)">${money(price(e))}</dd><small class="muted">Incluye cargos e IVA.</small></div></dl>${availability[String(e.id)]?.functions?.[String(functions[activeFunctionIndex]?.id??'1')]?.soldOut?'<button class="btn" id="buy" style="width:100%" disabled>Agotado</button><p class="muted small-note">Si alguien libera un lugar, la función vuelve a la venta automáticamente.</p>':'<button class="btn" id="buy" style="width:100%">Elegir boletos</button>'}<p style="font-size:13px;margin-top:16px;margin-bottom:0">Máximo ${Number(e.ticketLimit)||6} boletos por compra. Reserva de 10 minutos.</p></aside></div>`;$('#function').onchange=()=>{activeFunctionIndex=Number($('#function').value);detail(id)};$('#zone-choice').onchange=()=>{activeZoneName=$('#zone-choice').value;detail(id)};$('#buy').onclick=()=>{if(hold){toast('Tienes una compra en curso. Continúala o cancélala antes de empezar otra.');go('en-curso');return}activeEvent=e.id;selectedFunction={...functions[activeFunctionIndex]};selected=[];quantity=1;paid=false;go('localidades/'+e.id)}}
const occupied=new Proxy(['A3','A4','B6','C2','C7','D5'],{get(target,key){if(key==='includes')return id=>{const current=evt();return current.zones?.length?(current.blockedSeats||[]).includes(id):target.includes(id)||(current.blockedSeats||[]).includes(id)};return Reflect.get(target,key)}});
// Seat map (T08 + Entrega 3): a click holds the seat on the server at once; seats other
// buyers hold show a lock, and a lost race shows where to look next.
const ICON={
  lock:'<svg class="ico" viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="M4.5 7V5.2a3.5 3.5 0 0 1 7 0V7h.6c.8 0 1.4.6 1.4 1.4v5.2c0 .8-.6 1.4-1.4 1.4H3.9c-.8 0-1.4-.6-1.4-1.4V8.4C2.5 7.6 3.1 7 3.9 7h.6Zm1.6 0h3.8V5.2a1.9 1.9 0 0 0-3.8 0V7Z"/></svg>',
  check:'<svg class="ico" viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="7" fill="currentColor"/><path d="m4.8 8.3 2.2 2.2 4.3-4.6" fill="none" stroke="var(--seat-check,#fff)" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/></svg>',
  star:'<svg class="ico" viewBox="0 0 16 16" aria-hidden="true"><path fill="currentColor" d="m8 1.6 1.9 4 4.4.5-3.3 3 .9 4.3L8 11.2l-3.9 2.2.9-4.3-3.3-3 4.4-.5L8 1.6Z"/></svg>',
  info:'<svg class="ico" viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="7" fill="currentColor"/><path d="M8 7v4.2M8 4.6v.1" stroke="var(--bg)" stroke-width="1.8" stroke-linecap="round"/></svg>',
  alert:'<svg class="ico" viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="7" fill="currentColor"/><path d="M8 4.4v4.4M8 11.3v.1" stroke="var(--bg)" stroke-width="1.8" stroke-linecap="round"/></svg>',
  clock:'<svg class="ico" viewBox="0 0 16 16" aria-hidden="true"><circle cx="8" cy="8" r="6.2" fill="none" stroke="currentColor" stroke-width="1.6"/><path d="M8 4.8V8l2.2 1.4" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round"/></svg>',
};
const SAMPLE_MAP=['A','B','C','D'].flatMap(row=>Array.from({length:8},(_,i)=>`${row}${i+1}`));
const REALTIME='<strong>Actualización en tiempo real activada:</strong> los asientos pueden cambiar de estado mientras seleccionas.';
let lastExpired=null,othersClock=null;
try{lastExpired=JSON.parse(sessionStorage.getItem('eticket-last-seats'))}catch{}
// When a seat hold expires its seats are remembered, so the map can say what happened to them.
function rememberExpired(h){if(!h||h.kind!=='seat'||!h.seats?.length)return;lastExpired={eventId:String(h.eventId),functionId:String(h.functionId),zone:h.zone,seats:[...h.seats]};try{sessionStorage.setItem('eticket-last-seats',JSON.stringify(lastExpired))}catch{}}
function forgetExpired(){lastExpired=null;try{sessionStorage.removeItem('eticket-last-seats')}catch{}}
const seatParts=seat=>({row:seat.match(/^[A-Z]+/)?.[0]||'A',n:Number(seat.replace(/^[A-Z]+/,''))||0});
// Nearest free seats to the ones that were lost: same row first, then the rows around it.
function nearestSeats(lostSeats,free,rows){const rowIndex=Object.fromEntries(rows.map((r,i)=>[r,i])),picked=[];for(const lost of lostSeats){const p=seatParts(lost);let best=null,score=Infinity;for(const seat of free){if(picked.includes(seat))continue;const q=seatParts(seat),s=Math.abs(q.n-p.n)+Math.abs((rowIndex[q.row]??99)-(rowIndex[p.row]??99))*3;if(s<score){best=seat;score=s}}if(best)picked.push(best)}return picked}

function seats(id){
  clearInterval(seatPoll);
  if(hold&&(hold.status!=='active'||String(hold.eventId)!==String(id))){toast('Tienes una compra en curso. Continúala o cancélala antes de empezar otra.');go('en-curso');return}
  if(hold){editingHold=hold.id;alignToHold()}else{editingHold='';activeEvent=Number(id)||1}
  const e=configureEvent(evt()),zone=e.zones?.find(z=>z.name===activeZoneName),limit=Math.max(1,Number(e.ticketLimit)||6);
  if(e.type!=='seat'){generalZone(e,zone,limit);return}
  if(!hold)selected=[];
  const fnId=String(selectedFunction?.id??'1'),target={eventId:String(e.id),functionId:fnId,zone:e.zone};
  const map=zone?.seats?.length?zone.seats:SAMPLE_MAP,rows=[...new Set(map.map(s=>seatParts(s).row))];
  const accessible=new Set(zone?.accessible?.length?zone.accessible:(!e.zones?.length?['D1','D2']:[]));
  const prior=lastExpired&&lastExpired.eventId===target.eventId&&lastExpired.functionId===target.functionId&&lastExpired.zone===target.zone?lastExpired.seats:[];
  const state={live:{sold:new Set(zone?.occupiedSeats||[]),held:new Set(),ready:false,snapshot:''},lost:new Set(),suggested:[],conflict:'',pending:'',banner:{type:'live',html:REALTIME},ownAt:0,priorChecked:false};
  const isFree=seat=>!occupied.includes(seat)&&!state.live.sold.has(seat)&&!state.live.held.has(seat)&&!selected.includes(seat);
  const statusOf=seat=>{
    if(state.pending===seat)return'pending';
    if(selected.includes(seat))return'mine';
    if(occupied.includes(seat))return'sold';
    if(state.live.sold.has(seat))return state.lost.has(seat)?'lost-sold':'sold';
    if(state.live.held.has(seat)||state.lost.has(seat))return state.lost.has(seat)?'lost-held':'held';
    return state.suggested.includes(seat)?'suggested':'free';
  };
  const LABEL={free:'disponible',suggested:'disponible, sugerido',mine:'seleccionado y apartado para ti',sold:'no disponible','lost-sold':'ya no disponible: lo compró otra persona',held:'apartado temporalmente por otra persona','lost-held':'apartado por otra persona',pending:'apartando…'};
  const grid=rows.map(row=>`<span aria-hidden="true">${row}</span>${map.filter(s=>seatParts(s).row===row).map(seat=>`<button class="seat" data-seat="${esc(seat)}" data-n="${seatParts(seat).n}">${seatParts(seat).n}</button>`).join('')}`).join('');
  app.innerHTML=`${back(hold?'resumen':'evento/'+e.id)}${steps(0)}<div class="split"><section><div class="eyebrow">${esc(e.name)} · ${esc(e.zone)}</div><h1 style="font-size:36px">Elige tu lugar</h1><div id="seat-banner" class="banner" role="status"></div><div class="panel seat-panel"><div class="stage">ESCENARIO</div><div class="seats">${grid}</div><div id="seat-popover" class="seat-popover" role="alert" hidden></div><div class="legend"><span><b>1</b>Disponible</span><span><b class="lg-mine">${ICON.check}</b>Seleccionado</span><span><b>×</b>No disponible</span><span><b class="lg-access">♿</b>Accesible</span><span><b class="lg-held">${ICON.lock}</b>Apartado temporalmente</span></div><p id="seat-tip" class="seat-tip" hidden>${ICON.info}<span>Te recomendamos elegir asientos cercanos disponibles para continuar.</span></p><p class="seat-note">Las localidades accesibles están identificadas con ♿. Los asientos de cortesía y prensa están bloqueados. Máximo ${limit} asientos.</p></div></section><aside class="panel summary"><h2>Tu selección</h2><p>${esc(e.name)}<br>${date(e.date)} · ${esc(e.hour)} h</p><div id="selection-summary"></div><div id="seat-notice"></div><button class="btn" id="to-summary" style="width:100%">Continuar al resumen</button><p class="seat-foot" id="seat-foot"></p></aside></div>`;
  const grid$=$('.seats');if(zone?.seatsPerRow&&grid$)grid$.style.gridTemplateColumns=`16px repeat(${zone.seatsPerRow},minmax(0,1fr))`;
  function suggestions(){const free=map.filter(isFree),lostList=[...state.lost],back=prior.filter(s=>isFree(s));return [...new Set([...back,...nearestSeats(lostList,free.filter(s=>!back.includes(s)),rows)])]}
  function paint(){
    document.querySelectorAll('[data-seat]').forEach(b=>{const seat=b.dataset.seat,status=statusOf(seat),access=accessible.has(seat)&&(status==='free'||status==='suggested');
      b.className=`seat ${status}${access?' accessible':''}`;b.disabled=!['free','suggested','mine'].includes(status);b.setAttribute('aria-pressed',String(status==='mine'));
      b.setAttribute('aria-label',`Asiento ${seat}, ${LABEL[status]}${access?', accesible':''}`);
      b.innerHTML=status==='mine'?`${ICON.check}<span>${b.dataset.n}</span>`:status==='held'||status==='lost-held'?`${ICON.lock}<span>${b.dataset.n}</span>`:status==='sold'||status==='lost-sold'?'×':status==='suggested'?`${ICON.star}${state.suggested[0]===seat?'<span class="seat-tag">Sugerido</span>':''}`:access?'♿':b.dataset.n});
    const banner=$('#seat-banner');banner.className=`banner ${state.banner.type}`;banner.innerHTML=`${state.banner.type==='live'?'<span class="banner-dot" aria-hidden="true"></span>':state.banner.type==='success'?ICON.check:state.banner.type==='error'?ICON.alert:ICON.info}<span>${state.banner.html}</span>`;
    $('#seat-tip').hidden=!state.suggested.length;
    const n=selected.length;
    $('#selection-summary').innerHTML=`<div class="line"><span>Asientos</span><strong>${esc(selected.join(', ')||'Sin seleccionar')}</strong></div><div class="line"><span>Precio por boleto</span><strong>${money(price(e))}</strong></div><div class="line total"><span>Total</span><strong>${money(price(e)*n)}</strong></div>`;
    const lostSold=[...state.lost].filter(s=>state.live.sold.has(s)),lostHeld=[...state.lost].filter(s=>!state.live.sold.has(s)),list=a=>a.length>1?`${a.slice(0,-1).join(', ')} y ${a.at(-1)}`:a[0];
    let notice='';
    if(state.lost.size&&!state.conflict)notice=`<div class="notice warn">${ICON.alert}<div><strong>Los asientos elegidos anteriormente ya no están disponibles.</strong><p>${[lostSold.length?`${list(lostSold)} ${lostSold.length>1?'fueron comprados':'fue comprado'} por otro usuario.`:'',lostHeld.length?`${list(lostHeld)} ${lostHeld.length>1?'están apartados':'está apartado'} por otro usuario.`:''].join(' ')} Por favor, selecciona nuevos asientos disponibles para continuar.</p></div></div>`;
    else if(state.conflict)notice=`<div class="notice warn">${ICON.alert}<div><p>Tu selección se actualizó porque otro usuario reservó el asiento ${esc(state.conflict)}. Por favor, elige otro asiento si deseas más localidades.</p></div></div>`;
    else if(hold&&(Date.now()-state.ownAt<8000||!state.live.held.size))notice=`<div class="notice warn">${ICON.lock}<div><p>Tus asientos están protegidos mientras completas el proceso.</p><p class="notice-clock">${ICON.clock}<span>Reserva temporal detectada - <strong id="seat-hold-left">${clockText(holdLeft())}</strong> restantes</span></p></div></div>`;
    else if(state.live.held.size)notice=`<div class="notice warn">${ICON.lock}<div><p>Algunos asientos están en proceso de compra por otro usuario. Se liberan automáticamente si no completa su compra.</p>${othersClock?`<p class="notice-clock">${ICON.clock}<span>Reserva temporal detectada · <strong id="others-hold-left">${clockText(Math.max(0,othersClock.left-(performance.now()-othersClock.at)))}</strong> restantes</span></p>`:''}</div></div>`;
    $('#seat-notice').innerHTML=notice;
    const button=$('#to-summary');
    if(state.lost.size&&!state.conflict){button.textContent='Seleccionar nuevos asientos';button.disabled=false;button.dataset.mode='retry'}
    else{button.textContent=hold?'Continuar al resumen':'Continuar al resumen';button.disabled=!hold||!n;button.dataset.mode='go'}
    $('#seat-foot').textContent=n?'Precio final con cargo e IVA incluidos. Los asientos apartados temporalmente se liberan en unos minutos.':'Debes elegir al menos un asiento disponible para continuar. Los asientos apartados temporalmente se liberan en unos minutos.';
  }
  function popover(seat){const pop=$('#seat-popover'),button=document.querySelector(`[data-seat="${CSS.escape(seat)}"]`),panel=$('.seat-panel');pop.innerHTML=`${ICON.alert}<div><strong>No se pudo apartar ${esc(seat)}</strong><span>Otro usuario completó la selección primero.</span></div><button type="button" aria-label="Cerrar aviso">×</button>`;pop.hidden=false;if(button&&panel){const a=button.getBoundingClientRect(),p=panel.getBoundingClientRect();const above=a.top-p.top-pop.offsetHeight-12;pop.style.top=`${above>=8?above:a.bottom-p.top+12}px`;pop.style.left=`${Math.min(Math.max(8,a.left-p.left+a.width/2-pop.offsetWidth/2),p.width-pop.offsetWidth-8)}px`}pop.querySelector('button').onclick=()=>{pop.hidden=true};clearTimeout(pop.timer);pop.timer=setTimeout(()=>{pop.hidden=true},6000)}
  async function toggle(seat){
    if(!signed){authNext='localidades/'+e.id;toast('Inicia sesión para apartar tus asientos.');go('login');return}
    if(state.pending||holdBusy)return;
    const adding=!selected.includes(seat),next=adding?[...selected,seat]:selected.filter(s=>s!==seat);
    if(adding&&selected.length>=limit){state.banner={type:'error',html:`Puedes apartar hasta ${limit} asientos por compra.`};paint();return}
    state.pending=seat;state.conflict='';paint();holdBusy=true;
    try{
      const body={eventId:e.id,functionId:fnId,zone:e.zone,seats:next},first=!hold;
      const result=hold?await accountApi('holds/'+hold.id,body,'PUT'):await accountApi('holds',body);
      setHold(result.hold);selected=hold?[...hold.seats]:[];state.ownAt=Date.now();
      if(hold)forgetExpired();
      state.lost.delete(seat);state.suggested=state.lost.size?suggestions():[];
      state.banner=!hold?{type:'info',html:'Liberaste tus asientos. Ya no tienes lugares apartados.'}:first?{type:'success',html:'Tus asientos fueron apartados correctamente durante 10 minutos.'}:adding?{type:'success',html:`Apartamos el asiento ${esc(seat)}. El reloj sigue corriendo y no se reinicia.`}:{type:'info',html:`Liberaste el asiento ${esc(seat)}.`};
      if(hold)editingHold=hold.id;
    }catch(err){
      if(err.data?.hold){setHold(err.data.hold);toast(err.message);go('en-curso');return}
      if(err.status===410){rememberExpired(hold);setHold(null);go('expirado');return}
      if(err.data?.seat){state.conflict=err.data.seat;state.lost.add(err.data.seat);state.banner={type:'error',html:`El asiento ${esc(err.data.seat)} acaba de ser reservado por otro usuario. Tu selección se actualizó automáticamente.`};state.suggested=nearestSeats([err.data.seat],map.filter(s=>isFree(s)&&s!==err.data.seat),rows);popover(err.data.seat);refresh()}
      else state.banner={type:'error',html:esc(err.message)};
    }finally{state.pending='';holdBusy=false;paint()}
  }
  document.querySelectorAll('[data-seat]').forEach(b=>b.onclick=()=>toggle(b.dataset.seat));
  $('#to-summary').onclick=()=>{
    if($('#to-summary').dataset.mode==='retry'){state.lost.clear();forgetExpired();state.banner={type:'live',html:REALTIME};paint();$('.seat-panel').scrollIntoView({behavior:'smooth',block:'center'});return}
    if(hold&&selected.length){paid=false;paymentError='';go('resumen')}
  };
  // Seats held or freed in other browsers show up here without reloading.
  const token=liveSeats={},refresh=async()=>{try{
    const r=await accountApi(`availability?eventId=${encodeURIComponent(e.id)}&functionId=${encodeURIComponent(fnId)}&zone=${encodeURIComponent(e.zone)}`,null,'GET',true);
    if(liveSeats!==token)return;
    const sold=new Set(r.sold||r.occupied||[]),held=new Set(r.held||[]),snapshot=`${[...sold].sort()}|${[...held].sort()}`;
    const changed=state.live.ready&&snapshot!==state.live.snapshot&&Date.now()-state.ownAt>2500;
    state.live={sold,held,ready:true,snapshot};
    for(const seat of state.lost)if(!sold.has(seat)&&!held.has(seat)){state.lost.delete(seat);if(state.conflict===seat)state.conflict=''}
    othersClock=r.heldUntil?{at:performance.now(),left:Math.max(0,r.heldUntil-r.now)}:null;
    if(!state.priorChecked&&prior.length&&!hold){state.priorChecked=true;for(const seat of prior)if(sold.has(seat)||held.has(seat))state.lost.add(seat);state.suggested=suggestions();if(state.lost.size)state.banner={type:'info',html:'Actualizamos la disponibilidad en tiempo real: algunos asientos cambiaron de estado.'};else if(state.suggested.length)state.banner={type:'info',html:`Tus asientos anteriores (${esc(prior.join(', '))}) siguen disponibles. Puedes volver a apartarlos.`}}
    else if(changed&&!['error','success'].includes(state.banner.type))state.banner={type:'info',html:'Actualizamos la disponibilidad en tiempo real: algunos asientos cambiaron de estado.'};
    if(state.suggested.some(s=>!isFree(s)))state.suggested=suggestions();
    paint();
  }catch{}};
  paint();refresh();
  seatPoll=setInterval(()=>{if(liveSeats!==token||!location.hash.startsWith('#localidades/')){clearInterval(seatPoll);othersClock=null;return}if(document.visibilityState==='visible')refresh()},3000);
}
// General admission keeps a quantity picker; the hold is made when continuing.
function generalZone(e,zone,limit){
  let max=Math.max(1,Math.min(limit,Number(zone?.capacity)||6)),available=Math.max(0,(Number(zone?.capacity)||24)-(Number(zone?.sold)||0));
  app.innerHTML=`${back(hold?'resumen':'evento/'+e.id)}${steps(0)}<div class="split"><section><div class="eyebrow">${esc(e.name)} · ${esc(e.zone)}</div><h1 style="font-size:36px">Entradas de zona general</h1><div class="panel"><span class="badge">Zona general</span><h2 style="margin-top:20px">${esc(e.zone)}</h2><p><strong id="available">${available}</strong> lugares restantes.</p><div class="quantity"><button id="minus" aria-label="Quitar un boleto">−</button><output id="qty">${quantity}</output><button id="plus" aria-label="Agregar un boleto">+</button></div><p id="qty-help" style="text-align:center;font-size:14px"></p><div class="alert">Puedes elegir hasta ${max} boletos. La disponibilidad se confirma al reservar.</div></div><p id="selection-error" class="error" role="alert"></p></section><aside class="panel summary"><h2>Tu selección</h2><p>${esc(e.name)}<br>${date(e.date)} · ${esc(e.hour)} h</p><div id="selection-summary"></div>${hold?'<div class="alert">Estás cambiando los lugares de tu compra en curso. El reloj sigue corriendo y no se reinicia.</div>':''}<button class="btn" id="to-summary" style="width:100%">${hold?'Guardar cambios':'Continuar al resumen'}</button></aside></div>`;
  function update(){$('#selection-summary').innerHTML=`<div class="line"><span>Cantidad</span><strong>${quantity} boletos</strong></div><div class="line"><span>Zona</span><strong>${esc(e.zone)}</strong></div><div class="line"><span>Precio por boleto</span><strong>${money(price(e))}</strong></div><div class="line total"><span>Total</span><strong>${money(price(e)*quantity)}</strong></div>`;$('#to-summary').disabled=available<1;$('#qty').textContent=quantity;$('#minus').disabled=quantity<=1;$('#plus').disabled=quantity>=max;$('#available').textContent=available;$('#qty-help').textContent=`Quedarían ${Math.max(0,available-quantity)} lugares disponibles.`}
  $('#minus').onclick=()=>{quantity=Math.max(1,quantity-1);update()};$('#plus').onclick=()=>{quantity=Math.min(max,quantity+1);update()};
  $('#to-summary').onclick=()=>{if(!signed){authNext='reserva';go('login');return}reserve()};update();
  const token=liveSeats={},refresh=async()=>{try{const r=await accountApi(`availability?eventId=${encodeURIComponent(e.id)}&functionId=${encodeURIComponent(selectedFunction?.id??'1')}&zone=${encodeURIComponent(e.zone)}`,null,'GET',true);if(liveSeats!==token)return;available=r.available;max=Math.max(1,Math.min(limit,available));if(quantity>max)quantity=max;update()}catch{}};
  refresh();seatPoll=setInterval(()=>{if(liveSeats!==token||!location.hash.startsWith('#localidades/')){clearInterval(seatPoll);return}if(document.visibilityState==='visible')refresh()},5000);
}
async function reserve(){if(holdBusy)return;if(hold&&editingHold!==hold.id){toast('Tienes una compra en curso. Continúala o cancélala antes de empezar otra.');go('en-curso');return}const e=evt(),button=$('#to-summary'),label=button?.textContent,body={eventId:e.id,functionId:String(selectedFunction?.id??'1'),zone:e.zone,...(e.type==='seat'?{seats:[...selected]}:{quantity})};holdBusy=true;if(button){button.disabled=true;button.textContent='Apartando tus lugares…'}try{const result=hold?await accountApi('holds/'+hold.id,body,'PUT'):await accountApi('holds',body);setHold(result.hold);if(!result.hold){selected=[];quantity=1;toast('Compra cancelada. Localidades liberadas.');go('localidades/'+e.id);return}paid=false;paymentError='';go('resumen')}catch(err){if(err.data?.hold){setHold(err.data.hold);toast(err.message);go('en-curso');return}if(err.status===410){setHold(null);go('expirado');return}if(err.data?.seat){selected=selected.filter(s=>s!==err.data.seat);go('ocupado/'+encodeURIComponent(err.data.seat));return}toast(err.message)}finally{holdBusy=false;if(button){button.disabled=false;button.textContent=label}}}
function amounts(){const e=evt(),n=count(),rate=hold?.feeRate??feeRate,base=Math.round(e.base*n*100)/100,fee=Math.round(base*rate*100)/100,vat=Math.round((base+fee)*.16*100)/100;return{n,rate,base,fee,vat,total:Math.round((base+fee+vat)*100)/100}}
function breakdown(){const e=evt(),n=count(),rate=hold?.feeRate??feeRate,base=Math.round(e.base*n*100)/100,fee=Math.round(base*rate*100)/100,vat=Math.round((base+fee)*.16*100)/100,total=Math.round((base+fee+vat)*100)/100;return `<div class="line"><span>Zona elegida</span><strong>${esc(e.zone)} (${money(e.base)} por boleto)</strong></div><div class="line"><span>${n} boleto${n===1?'':'s'} × ${money(e.base)}</span><strong>${money(base)}</strong></div><div class="line"><span>Cargo por servicio (${Math.round(rate*1000)/10} %)</span><strong>${money(fee)}</strong></div><div class="line"><span>IVA (16 %)</span><strong>${money(vat)}</strong></div><div class="line total"><span>Total MXN (IVA incluido)</span><strong>${money(total)}</strong></div>`}
function orderInfo(editable=false){const e=evt(),list=e.type==='seat'?(editable?selected.map(s=>`<span class="hold-seat">${esc(s)}<button type="button" class="link-btn" data-remove="${esc(s)}" aria-label="Quitar asiento ${esc(s)}">Quitar</button></span>`).join(' '):esc(selected.join(', '))):`${quantity}${editable?' <button type="button" class="link-btn" data-remove="1" aria-label="Quitar un acceso">Quitar uno</button>':''}`;return `<h2>${esc(e.name)}</h2><p>${date(e.date)} · ${esc(e.hour)} h<br>${esc(e.venue)}, ${esc(e.city)}</p><div class="line"><span>${e.type==='seat'?'Asientos':'Accesos generales'}</span><strong>${list}</strong></div>${breakdown()}`}
function summary(){if(!hold){go('localidades/'+activeEvent);return}if(hold.status==='paying'){go('procesando');return}alignToHold();const e=evt();app.innerHTML=`${back('localidades/'+e.id)}${steps(1)}<h1 style="font-size:38px">Revisa tu compra</h1><div class="split"><section class="panel">${orderInfo(true)}<div class="actions"><button class="btn secondary" id="edit">Cambiar localidades</button></div></section><aside class="panel"><h2>Todo listo para continuar</h2><p>Revisa la fecha, la zona y tus boletos antes de pasar al pago.</p><div class="line total"><span>Tiempo restante de reserva</span><strong id="summary-clock">${clockText(holdLeft())}</strong></div><div class="alert" style="margin-top:12px">Tus localidades están apartadas mientras el reloj esté activo. Si quitas un lugar se libera al instante; el tiempo no se reinicia.</div><a class="btn" href="#pago" style="width:100%">Continuar al pago</a><button class="btn secondary" style="width:100%;margin-top:12px" id="cancel">Cancelar compra</button><p class="muted" style="font-size:13px;margin:16px 0 0">Modo sandbox: no se realizan cargos bancarios reales.</p></aside></div>`;$('#edit').onclick=()=>go('localidades/'+e.id);$('#cancel').onclick=()=>go('cancelar');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>removeFromHold(b.dataset.remove))}
async function removeFromHold(item){if(!hold||holdBusy)return;const e=evt(),body=e.type==='seat'?{seats:selected.filter(s=>s!==item)}:{quantity:quantity-1};holdBusy=true;document.querySelectorAll('[data-remove]').forEach(b=>b.disabled=true);try{const result=await accountApi('holds/'+hold.id,body,'PUT');setHold(result.hold);if(!result.hold){selected=[];quantity=1;toast('Compra cancelada. Localidades liberadas.');go('localidades/'+e.id);return}toast(e.type==='seat'?`Asiento ${item} liberado.`:'Se liberó un acceso.');render()}catch(err){handleHoldError(err)}finally{holdBusy=false}}
function auth(mode) { renderAuth(mode,{app,back,go,toast,useAccount,completeAuth,onReset:()=>{paid=false;}}); }
async function rolePanel(sub=[]){await renderRolePanel({app,user:currentUser,toast,sub,catalogEvents:events,eventName:id=>events.find(e=>String(e.id)===String(id))?.name||`Evento ${id}`});}
async function syncManagedEvents(){try{const listing=await accountApi('events',null,'GET');availability=listing.availability||{};for(const item of listing.events){if(item.status!=='published')continue;const mapped={...item,id:Number(item.id)||item.id,base:Number(item.base||item.zones?.[0]?.price||0),zone:item.zone||item.zones?.[0]?.name||'General',type:item.type||item.zones?.[0]?.type||'general',class:item.class||'p1',tag:item.tag||'EN VIVO',city:item.city||'',hour:item.hour||item.functions?.[0]?.hour||'20:00',date:item.date||item.functions?.[0]?.date||'',venue:item.venue||'',artist:item.artist||item.organizer||'',desc:item.desc||item.description||'',category:item.category||'Eventos'};const at=events.findIndex(e=>String(e.id)===String(mapped.id));if(at>=0)events[at]=mapped;else events.push(mapped)}if(location.hash==='#cartelera')catalog()}catch{}}
function completeAuth(){const next=authNext;authNext='';if(hold){toast('Tienes una compra en curso.');go('en-curso');return}if(next==='reserva'&&count())reserve();else go(next||'boletos')}
function payment(){
  if(!hold){go('localidades/'+activeEvent);return}
  if(hold.status==='paying'){go('procesando');return}
  alignToHold();
  const e=evt(), totalAmount=amounts().total;
  app.innerHTML=`${back('resumen')}${steps(2)}<h1 style="font-size:38px">Pago seguro en sandbox</h1><div class="split"><section class="panel"><h2>Formulario de tarjeta (Sandbox)</h2><div class="alert"><p style="margin:0">Modo de pruebas activo. El número de tarjeta se tokeniza en tu navegador y nunca llega ni se almacena en nuestro servidor.</p></div><div class="test-cards" style="margin:16px 0"><p style="font-size:13px;font-weight:600;margin-bottom:8px">Tarjetas de prueba:</p><div class="actions" style="margin:0"><button type="button" class="btn secondary small fill-card" data-card="4242424242424242" data-last4="4242">Aprobada (•••• 4242)</button><button type="button" class="btn secondary small fill-card" data-card="4000000000000002" data-last4="0002">Rechazo fondos (•••• 0002)</button><button type="button" class="btn secondary small fill-card" data-card="4000000000009999" data-last4="9999">Sin boletos RN-12 (•••• 9999)</button><button type="button" class="btn secondary small fill-card" data-card="4000000000000069" data-last4="0069">Aprobada, reembolso falla (•••• 0069)</button></div></div><form id="card-pay-form"><div class="field"><label for="card-holder">Nombre en la tarjeta</label><input id="card-holder" required value="${esc(user||'Comprador Demo')}" maxlength="80" autocomplete="cc-name"></div><div class="field"><label for="card-number">Número de tarjeta</label><input id="card-number" required placeholder="4242 •••• •••• 4242" value="4242 •••• •••• 4242" maxlength="19" autocomplete="cc-number"></div><div class="split" style="margin:0"><div class="field"><label for="card-exp">Vencimiento (MM/AA)</label><input id="card-exp" required placeholder="12/28" value="12/28" maxlength="5" autocomplete="cc-exp"></div><div class="field"><label for="card-cvc">CVC</label><input id="card-cvc" required placeholder="123" value="123" maxlength="4" autocomplete="cc-csc"></div></div>${legalSummary}<label class="inline-check" for="terms-refunds" style="margin:16px 0"><input id="terms-refunds" type="checkbox"><span>Acepto los <a href="#terminos" target="_blank" rel="noopener">términos</a>, la <a href="#reembolsos" target="_blank" rel="noopener">política de reembolsos</a> y el <a href="#privacidad" target="_blank" rel="noopener">aviso de privacidad</a>.</span></label><p class="error" id="payment-error" role="alert">${paymentError}</p><button class="btn" id="pay-btn" type="submit" style="width:100%" disabled>Confirmar pago de ${money(totalAmount)}</button></form></section><aside class="panel summary">${orderInfo()}<div class="line total" style="margin-top:12px"><span>Tiempo de reserva</span><strong id="payment-clock">${clockText(holdLeft())}</strong></div></aside></div>`;
  const termsCheckbox=$('#terms-refunds'), payButton=$('#pay-btn'), form=$('#card-pay-form'), errorEl=$('#payment-error');
  termsCheckbox.onchange=()=>{payButton.disabled=!termsCheckbox.checked};
  document.querySelectorAll('.fill-card').forEach(b=>b.onclick=()=>{
    const raw=b.dataset.card;
    $('#card-number').value=raw.replace(/(\d{4})/g,'$1 ').trim();
    $('#card-exp').value='12/28';
    $('#card-cvc').value='123';
  });
  form.onsubmit=async ev=>{
    ev.preventDefault();
    if(!termsCheckbox.checked||payButton.disabled)return;
    const cardInput=$('#card-number').value.replace(/\D/g,'')||'4242';
    const last4=cardInput.slice(-4)||'4242';
    const brand=cardInput.startsWith('4')?'VISA':cardInput.startsWith('5')?'MASTERCARD':'VISA';
    const token='tok_sandbox_'+Date.now()+'_'+Math.random().toString(36).slice(2);
    // T07.3: Clear sensitive card numbers from memory and DOM immediately
    $('#card-number').value='';
    $('#card-cvc').value='';
    // T07.6: Disable button on first click to avoid double submit
    payButton.disabled=true;
    payButton.textContent='Procesando pago seguro en sandbox…';
    errorEl.textContent='';
    const idempotencyKey='ik_'+hold.id+'_'+Date.now()+'_'+Math.random().toString(36).slice(2);
    try{
      const res=await accountApi('payments/charge',{holdId:hold.id,token,last4,brand,idempotencyKey});
      if(res.ok&&res.order){
        orders=(await accountApi('orders',null,'GET')).orders;
        paid=false;
        setHold(null);
        toast('Pago aprobado por la pasarela.');
        go('confirmacion/'+res.order.id);
        return;
      }
    }catch(err){
      const data=err.data;
      if(data?.cancelled){
        setHold(null);
        toast('Has alcanzado 3 intentos de pago fallidos. Tus lugares se liberaron.');
        go('cartelera');
        return;
      }
      if(data?.hold)setHold(data.hold);
      errorEl.textContent=err.message||'El banco rechazó la transacción.';
      payButton.disabled=!termsCheckbox.checked;
      payButton.textContent=`Confirmar pago de ${money(totalAmount)}`;
    }
  };
}
function confirmation(id){
  const o=orders.find(o=>o.id===id), e=o&&events.find(e=>String(e.id)===String(o.eventId));
  if(!o||!e){missing();return}
  const breakdown=o.breakdown||{};
  app.innerHTML=`${steps(3)}<section class="panel" style="max-width:720px;margin:20px auto"><div style="text-align:center"><div class="eyebrow">Comprobante de compra · Sandbox</div><h1 style="font-size:40px;margin-bottom:8px">¡Pago confirmado!</h1><p>Tus boletos para <strong>${esc(e.name)}</strong> han sido emitidos con éxito.</p></div><div class="panel summary" style="margin:24px 0;background:rgba(255,255,255,0.02)"><h3>Comprobante de transacción</h3><div class="line"><span>Número de confirmación</span><strong>${esc(o.id)}</strong></div><div class="line"><span>Fecha y hora</span><strong>${new Date(o.time).toLocaleString('es-MX')}</strong></div><div class="line"><span>Método de pago</span><strong>Tarjeta ${esc(o.payment?.brand||'VISA')} terminada en •••• ${esc(o.payment?.last4||'4242')}</strong></div><div class="line"><span>Referencia de pasarela</span><small class="muted">${esc(o.payment?.transactionId||'pay_sandbox')}</small></div><div class="line"><span>Zona y boletos</span><strong>${esc(o.zone||e.zone)} (${o.tickets.length} boletos)</strong></div><hr style="border:0;border-top:1px solid rgba(255,255,255,0.1);margin:12px 0"><div class="line"><span>Subtotal boletos</span><strong>${money(breakdown.base||(e.base*o.tickets.length))}</strong></div><div class="line"><span>Cargo por servicio (10 %)</span><strong>${money(breakdown.fee||Math.round((breakdown.base||e.base*o.tickets.length)*0.1*100)/100)}</strong></div><div class="line"><span>IVA (16 %)</span><strong>${money(breakdown.vat||Math.round(((breakdown.base||e.base*o.tickets.length)+breakdown.fee)*0.16*100)/100)}</strong></div><div class="line total"><span>Total cobrado en sandbox</span><strong style="color:var(--accent,#e94560);font-size:22px">${money(o.total)} MXN</strong></div></div><p style="text-align:center;font-size:13px;color:var(--muted)">Comprobante emitido en ambiente sandbox. Este comprobante coincide exactamente con lo cobrado por la pasarela.</p><div class="alert" style="text-align:center">Te enviamos este comprobante y un PDF por boleto a ${esc(currentUser?.email||'tu correo')}. También puedes descargarlos cuando quieras en «Mis boletos».</div><div class="actions" style="justify-content:center"><a class="btn" href="#boletos">Ver mis boletos con QR</a><a class="btn secondary" href="#cartelera">Volver a cartelera</a></div></section>`;
}
function tickets(){if(!signed)authNext='boletos';renderTickets({app,user:currentUser,signed,back,toast,go})}
function history(){if(!signed){authNext='historial';go('login');return}renderHistory({app,back,toast,events})}
function transfer(id){if(!signed){authNext='transferir/'+id;go('login');return}renderTransfer({app,ticketId:id,back,toast,go})}
function cancel(){if(!hold){go('cartelera');return}if(hold.status==='paying'){toast('Tu pago está en proceso. Espera su resultado.');go('procesando');return}app.innerHTML=`${back('resumen')}<section class="panel form-card"><h1 style="font-size:32px">¿Cancelar esta compra?</h1><p>Tus localidades se liberarán al instante y podrás comenzar otra compra.</p><button class="btn" id="confirm-cancel" style="width:100%">Sí, cancelar compra</button><a class="btn secondary" href="#resumen" style="width:100%;margin-top:12px">Continuar mi compra</a></section>`;$('#confirm-cancel').onclick=async()=>{if(!hold){go('cartelera');return}const b=$('#confirm-cancel');b.disabled=true;try{await accountApi(`holds/${hold.id}/cancel`,{});setHold(null);selected=[];quantity=1;paid=false;go('cartelera');toast('Compra cancelada. Localidades liberadas.')}catch(err){b.disabled=false;handleHoldError(err)}}}
function expire(){rememberExpired(hold);paid=false;setHold(null);go('expirado')}
function expired(){app.innerHTML=`<section class="panel form-card"><div class="eyebrow">Tiempo de reserva terminado</div><h1 style="font-size:34px">Tu reserva expiró</h1><p>Pasaron los 10 minutos. Los lugares se liberaron y no se realizó ningún cobro. Elige tus boletos otra vez para comprobar la disponibilidad.</p><button class="btn" id="again">Volver a elegir boletos</button></section>`;$('#again').onclick=()=>{selected=[];quantity=1;go('localidades/'+activeEvent)}}
function tick(){const others=document.getElementById('others-hold-left');if(others&&othersClock)others.textContent=clockText(Math.max(0,othersClock.left-(performance.now()-othersClock.at)));const bar=$('#timerbar');if(!hold){bar.hidden=true;barKey='';return}const left=holdLeft(),route=routeName(),paying=hold.status==='paying';
  // At zero the server decides: it answers expired (released) or "En pago" (seats kept).
  if(!paying&&left<=0){bar.hidden=true;barKey='';if(!expiring){expiring=true;const id=hold.id;syncHold().then(result=>{expiring=false;if(!result&&hold?.id===id&&hold.status==='active'&&holdLeft()<=0)expire()})}return}
  const key=`${hold.id}|${hold.status}|${route}`;if(barKey!==key){barKey=key;const link=['resumen','pago','procesando','en-curso','cancelar'].includes(route)?'':`<a href="#${paying?'procesando':'resumen'}">Continuar compra</a>`;bar.innerHTML=`<strong id="timer-text"></strong>${link}${paying?'':'<button id="timer-cancel" type="button">Cancelar compra</button>'}`;$('#timer-cancel')?.addEventListener('click',()=>go('cancelar'))}
  bar.hidden=false;$('#timer-text').textContent=paying?(left>0?`En pago · ${clockText(left)} · Tus lugares siguen apartados mientras se confirma el pago.`:'En pago · El tiempo terminó, pero tus lugares siguen apartados hasta conocer el resultado del pago.'):`Reserva: ${clockText(left)}${left<=120000?' · Quedan menos de 2 minutos. Completa tu compra.':''}`;
  for(const id of ['resume-left','processing-left','summary-clock','payment-clock','seat-hold-left']){const el=document.getElementById(id);if(el)el.textContent=clockText(left)}
  if(!paying&&left<=120000&&!warning){warning=true;toast('Quedan 2 minutos o menos para completar tu compra.')}}
function resumeView(){if(!hold){go('cartelera');return}alignToHold();const e=evt(),paying=hold.status==='paying';app.innerHTML=`<section class="panel form-card"><div class="eyebrow">${paying?'Pago en proceso':'Compra en curso'}</div><h1 style="font-size:34px">Tienes una compra en curso</h1><p><strong>${esc(e.name)}</strong><br>${date(e.date)} · ${esc(e.hour)} h · ${esc(e.venue)}, ${esc(e.city)}</p><div class="line"><span>Zona</span><strong>${esc(e.zone)}</strong></div><div class="line"><span>${e.type==='seat'?'Asientos':'Accesos generales'}</span><strong>${e.type==='seat'?esc(selected.join(', ')):quantity}</strong></div><div class="line total"><span>Tiempo restante</span><strong id="resume-left">${clockText(holdLeft())}</strong></div><div class="alert">${paying?'Tu pago se está procesando. Tus lugares siguen apartados hasta conocer el resultado.':'El reloj no se reinicia al recargar, cambiar de pestaña o de dispositivo. Continúa con el tiempo que te queda o cancela para liberar tus lugares.'}</div><a class="btn" href="#${paying?'procesando':'resumen'}" style="width:100%">Continuar compra</a>${paying?'':'<a class="btn secondary" href="#cancelar" style="width:100%;margin-top:12px">Cancelar compra</a>'}<div class="actions" style="justify-content:center"><a href="#cartelera">Seguir explorando</a></div></section>`}
function navigation(){app.innerHTML=`${back('inicio')}<div class="eyebrow">Visitante y comprador</div><h1 style="font-size:38px">Mapa de navegación</h1><p>Cada pantalla está enlazada con su flujo. Las vistas de compra requieren una selección y una reserva activa.</p><div class="map-grid"><section class="panel"><h2>1. Descubrir</h2><a href="#inicio">Inicio y destacados</a><a href="#cartelera">Cartelera, búsqueda y 4 filtros</a><a href="#evento/1">Detalle, función, zona y precio</a><p>Inicio → Cartelera → Detalle → Localidades</p></section><section class="panel"><h2>2. Identificarse</h2><a href="#registro">Registro</a><a href="#login">Inicio de sesión</a><a href="#recuperar">Recuperar contraseña</a><p>Registro → Compra<br>Inicio de sesión → Compra</p></section><section class="panel"><h2>3. Comprar</h2><a href="#evento/1">Asientos numerados</a><a href="#evento/3">Zona general</a><p>Localidades → Resumen y reloj → Pago → Confirmación</p><p>Resumen ↔ Localidades<br>Pago ↔ Resumen<br>Reserva → Cancelar / Tiempo expirado</p><a href="#en-curso">Compra en curso</a><p>Volver con una compra abierta → Compra en curso → Resumen o Pago</p></section><section class="panel"><h2>4. Después de comprar</h2><a href="#boletos">Mis boletos, QR y PDF</a><a href="#historial">Historial y reembolsos</a><p>Mis boletos → Transferir (hasta 24 h antes) → Mis boletos</p><p>Cambio de fecha → Pedir reembolso (10 días)</p></section><section class="panel"><h2>5. Personal y organización</h2><a href="#panel">Panel según tu rol</a><p>Taquilla → Evento y puerta → Escáner<br>Organizador → Panel del evento → Ventas, asistencia, personal, cambios<br>Administración → Reportes, usuarios, reembolsos, cancelaciones, bitácora</p></section><section class="panel"><h2>6. Información legal</h2><a href="#privacidad">Aviso de privacidad</a><a href="#terminos">Términos y condiciones</a><a href="#reembolsos">Política de reembolsos</a></section></div>`}
function taken(seat=''){let label='';try{label=decodeURIComponent(seat)}catch{}app.innerHTML=`<section class="panel form-card"><h1 style="font-size:32px">Ese asiento ya no está disponible</h1><p>Otra persona apartó ${label?`el asiento ${esc(label)}`:'ese asiento'} antes de que confirmaras. No se realizó ningún cargo. Elige otro lugar disponible para continuar.</p><a class="btn" href="#localidades/${encodeURIComponent(activeEvent)}">Elegir otro asiento</a></section>`}
function processing(){if(!hold){go('cartelera');return}if(hold.status!=='paying'){go('pago');return}alignToHold();const e=evt();app.innerHTML=`${steps(2)}<section class="panel form-card"><div class="eyebrow">Pasarela sandbox</div><h1 style="font-size:32px">Pago en proceso</h1><p role="status">La pasarela está confirmando tu pago. Mientras tanto tus lugares siguen apartados, aunque el reloj llegue a cero (máximo 5 minutos).</p><div class="line"><span>${esc(e.name)} · ${esc(e.zone)}</span><strong>${e.type==='seat'?esc(selected.join(', ')):quantity+' accesos'}</strong></div><div class="line total"><span>Tiempo de la reserva</span><strong id="processing-left">${clockText(holdLeft())}</strong></div><div class="alert">Si el pago se aprueba verás tu confirmación y tus boletos; si no hay respuesta en 5 minutos, los lugares se liberan sin cobro.</div><div class="actions"><button class="btn" id="refresh-payment">Actualizar estado</button><a class="btn secondary" href="#boletos">Ir a mis boletos</a></div></section>`;$('#refresh-payment').onclick=async()=>{await syncHold();if(hold?.status==='paying')toast('El pago sigue en proceso.')}}
function validate(code){app.innerHTML=`${back('boletos')}<section class="panel form-card"><h1 style="font-size:30px">QR de demostración</h1><p>Código: ${esc(code||'Sin código')}</p><div class="alert">Este QR identifica una muestra del prototipo. No concede acceso a ningún evento real.</div><a class="btn" href="#boletos">Consultar mis boletos</a></section>`}
function missing(){app.innerHTML=`<div class="empty"><h1 style="font-size:34px">Esta página no está disponible</h1><p>Vuelve a la cartelera para continuar.</p><a class="btn" href="#cartelera">Ir a cartelera</a></div>`}
function render(){stopScanner();const [route='inicio',a,b]=location.hash.slice(1).split('/');$('#account').textContent=signed?(currentUser.role==='comprador'?'Mi cuenta':'Panel'):'Iniciar sesión';$('#account').href=signed?(currentUser.role==='comprador'?'#panel':'#panel'):'#login';$('#logout').hidden=!signed;switch(route||'inicio'){case'inicio':home();break;case'cartelera':catalog();break;case'evento':detail(a);break;case'localidades':seats(a);break;case'resumen':summary();break;case'login':case'registro':case'verificacion':case'recuperar':case'restablecer':auth(route);break;case'panel':rolePanel([a,b].filter(Boolean).map(decodeURIComponent));break;case'pago':payment();break;case'confirmacion':confirmation(a);break;case'boletos':tickets();break;case'historial':history();break;case'transferir':transfer(a);break;case'privacidad':case'terminos':case'reembolsos':renderLegal(app,route,back);break;case'cancelar':cancel();break;case'expirado':expired();break;case'en-curso':resumeView();break;case'mapa':navigation();break;case'revision':home();break;case'ocupado':taken(a);break;case'procesando':processing();break;case'validar':validate(a);break;default:missing()}tick();window.scrollTo(0,0);app.focus({preventScroll:true})}
$('#logout').onclick=logout;
async function initialize() {
  try {const result=await accountApi('auth/me',null,'GET');await useAccount(result.user);try{feeRate=(await accountApi('settings',null,'GET')).serviceFeeRate}catch{}const listing=await accountApi('events',null,'GET');availability=listing.availability||{};for(const item of listing.events){if(item.status!=='published')continue;const mapped={...item,id:Number(item.id)||item.id,base:Number(item.base||item.zones?.[0]?.price||0),zone:item.zone||item.zones?.[0]?.name||'General',type:item.type||item.zones?.[0]?.type||'general',class:item.class||'p1',tag:item.tag||'EN VIVO',city:item.city||'',hour:item.hour||'20:00',venue:item.venue||'',artist:item.artist||item.organizer||'',desc:item.desc||item.description||'',category:item.category||'Eventos'};const at=events.findIndex(e=>String(e.id)===String(mapped.id));if(at>=0)events[at]=mapped;else events.push(mapped);}}
  catch(err){toast(err.message);}
  window.addEventListener('hashchange',()=>{render();if(location.hash==='#cartelera')syncManagedEvents();if(location.hash.startsWith('#localidades/')){const e=evt(),zone=e.zones?.find(z=>z.name===activeZoneName),grid=$('.seats');if(grid&&zone?.seatsPerRow)grid.style.gridTemplateColumns=`16px repeat(${zone.seatsPerRow},minmax(0,1fr))`;if(zone&&Number(zone.capacity)===0&&$('#to-summary'))$('#to-summary').disabled=true}});setInterval(tick,1000);
  // K-09: whoever comes back (reload, another tab or device) sees the open purchase first.
  if(hold&&!purchaseRoutes.includes(routeName())&&!LEGAL[routeName()])go('en-curso');else render();
  setInterval(async()=>{if(document.visibilityState!=='visible'||!['inicio','cartelera','evento'].includes(routeName()))return;const before=JSON.stringify(availability);await syncManagedEvents();if(before!==JSON.stringify(availability)&&['inicio','cartelera','evento'].includes(routeName())&&!document.activeElement?.closest?.('form'))render()},30000);
  setInterval(()=>{if(signed&&document.visibilityState==='visible')syncHold(true)},15000);
  document.addEventListener('visibilitychange',()=>{if(signed&&document.visibilityState==='visible')syncHold(true)});
  if(holdChannel)holdChannel.onmessage=()=>{if(signed)syncHold(true)};
}
let lastUserActivity=Date.now();
for(const eventName of ['pointerdown','keydown','touchstart','scroll'])document.addEventListener(eventName,()=>{lastUserActivity=Date.now()},{passive:true});
setInterval(async()=>{if(!signed||Date.now()-lastUserActivity>300000)return;try{const result=await accountApi('auth/me',null,'GET');if(!result.user){await useAccount(null);toast('Tu sesión venció. Inicia sesión nuevamente.');go('login')}}catch{}},300000);
initialize();
