import { accountApi } from './account-ui.js';
import { renderScanner } from './scanner-ui.js';
import { renderEventDashboard } from './organizer-ui.js';
import { adminTabs, renderAdminTab } from './admin-ui.js';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const showError=e=>{const el=$('#role-error');if(el)el.textContent=e.message};
export async function renderRolePanel({app,user,toast,eventName=id=>`Evento ${id}`,sub=[],catalogEvents=[]}){
  if(!user){app.innerHTML='<section class="panel form-card"><h1>Inicia sesión para continuar</h1><a class="btn" href="#login">Iniciar sesión</a></section>';return;}
  if(user.role==='taquilla'){await renderScanner({app,user,toast,params:sub});return;}
  if(sub[0]==='evento'&&['organizador','administrador'].includes(user.role)){await renderEventDashboard({app,user,eventId:sub[1],toast,backHref:user.role==='administrador'?'#panel/eventos':'#panel'});return;}
  if(user.role==='comprador'){
    app.innerHTML=`<section class="panel form-card"><div class="eyebrow">Mi cuenta</div><h1>Solicitar cuenta de organizador</h1><p>La administración revisará tu solicitud. Mientras esté pendiente no podrás crear eventos.</p><p id="role-error" class="error" role="alert"></p>${user.organizerStatus==='pending'?'<div class="alert">Tu solicitud está en revisión.</div>':user.organizerStatus==='rejected'?`<div class="alert">Solicitud rechazada: ${esc(user.organizerReason||'Sin motivo indicado')}. Puedes volver a solicitarla.</div>`:''}<button class="btn" id="request-organizer" ${user.organizerStatus==='pending'?'disabled':''}>Enviar solicitud</button></section>`;
    $('#request-organizer').onclick=async()=>{try{await accountApi('auth/organizer-request',{});toast('Solicitud enviada.');location.reload()}catch(e){showError(e)}};return;
  }
  if(user.role==='organizador'){
    let data,venueData;try{[data,venueData]=await Promise.all([accountApi('events',null,'GET'),accountApi('organizer/venues',null,'GET')])}catch(e){app.innerHTML=`<section class="panel"><p>${esc(e.message)}</p></section>`;return;}
    const mine=data.events.filter(e=>e.ownerId===user.id||e.status!=='published');let editing=null;
    app.innerHTML=`<div class="section-head"><div><div class="eyebrow">Organizador</div><h1>Mis eventos</h1></div><button class="btn" id="new-event">Crear evento</button></div><p id="role-error" class="error" role="alert"></p><div class="cards">${mine.map(e=>`<article class="panel"><span class="badge">${esc(e.status)}</span><h2>${esc(e.name)}</h2><p>${esc(e.date||'')} · ${esc(e.venue||'')}</p>${e.reviewReason?`<p class="error">Motivo: ${esc(e.reviewReason)}</p>`:''}${['published','cancelled'].includes(e.status)?`<a class="btn small" href="#panel/evento/${encodeURIComponent(e.id)}">Panel del evento</a> `:''}${e.status==='cancelled'?'':`<button class="btn secondary small edit-event" data-id="${esc(e.id)}">Editar</button> <button class="btn secondary small submit-event" data-id="${esc(e.id)}" ${e.status==='review'?'disabled':''}>Enviar a revisión</button> <button class="btn secondary small delete-event" data-id="${esc(e.id)}">Eliminar</button>`}</article>`).join('')||'<div class="empty"><p>Aún no tienes eventos. Crea un borrador para comenzar.</p></div>'}</div><div id="event-editor"></div>`;
    $('#new-event').onclick=()=>{editing=null;editor()};
    document.querySelectorAll('.edit-event').forEach(b=>b.onclick=()=>{editing=mine.find(e=>String(e.id)===b.dataset.id);editor()});
    document.querySelectorAll('.delete-event').forEach(b=>b.onclick=async()=>{try{await accountApi(`events/${b.dataset.id}/delete`,{});toast('Evento eliminado.');renderRolePanel({app,user,toast,eventName,sub,catalogEvents})}catch(e){showError(e)}});
    document.querySelectorAll('.submit-event').forEach(b=>b.onclick=async()=>{try{await accountApi(`events/${b.dataset.id}/submit`,{});toast('Evento enviado a revisión.');renderRolePanel({app,user,toast,eventName,sub,catalogEvents})}catch(e){showError(e)}});
    function editor(){
      const target=$('#event-editor');
      target.innerHTML=`<section class="panel form-card"><h2>${editing?'Editar borrador':'Crear evento'}</h2><form id="event-form"><div class="field"><label>Nombre</label><input name="name" required maxlength="100"></div><div class="field"><label>Artista u organizador</label><input name="artist" required maxlength="100"></div><div class="field"><label>Categoría</label><input name="category" required maxlength="40"></div><div class="field"><label>Ciudad</label><input name="city" required maxlength="60"></div><div class="field"><label>Recinto</label>${venueData.venues.length?`<select name="venue" required>${venueData.venues.map(v=>`<option value="${esc(v.name)}">${esc(v.name)} · ${esc(v.city)}</option>`).join('')}</select>`:'<input name="venue" required maxlength="100">'}</div><div class="field"><label>Funciones (una por línea: AAAA-MM-DD,HH:MM)</label><textarea name="functions" placeholder="2026-11-14,20:00" required></textarea></div><div class="field"><label>Descripción</label><textarea name="desc" maxlength="1000"></textarea></div><div class="field"><label>Zonas (una por línea: nombre,precio,cupo,accesibles,filas,asientos por fila)</label><textarea name="zones" placeholder="Preferente,450,120,6,10,12\nGeneral,280,300,0,0,0" required></textarea></div><div class="field"><label>Asientos de cortesía/prensa bloqueados (separados por coma)</label><input name="blockedSeats" placeholder="A1,A2"></div><div class="field"><label>Límite de boletos por compra</label><input name="ticketLimit" type="number" min="1" max="6" value="6" required></div><div class="field"><label>Inicio de venta</label><input name="saleStart" type="datetime-local" required></div><div class="field"><label>Fin de venta</label><input name="saleEnd" type="datetime-local" required></div><p id="event-error" class="error" role="alert"></p><button class="btn">Guardar como borrador</button></form></section>`;
      const form=$('#event-form');if(editing){form.dataset.id=editing.id;for(const key of ['name','artist','category','city','venue','desc','ticketLimit','saleStart','saleEnd'])if(form.elements[key])form.elements[key].value=editing[key]??'';form.elements.functions.value=(editing.functions||[{date:editing.date,hour:editing.hour}]).map(fn=>`${fn.date},${fn.hour}`).join('\n');form.elements.zones.value=(editing.zones||[]).map(z=>`${z.name},${z.price},${z.capacity},${z.accessible?.length||0},${z.rows||0},${z.seatsPerRow||8}`).join('\n');form.elements.blockedSeats.value=(editing.blockedSeats||[]).join(',')}
      if(editing&&form.elements.venue instanceof HTMLSelectElement&&!venueData.venues.some(v=>v.name===editing.venue))form.elements.venue.add(new Option(editing.venue,editing.venue));
      if(form.elements.venue instanceof HTMLSelectElement){const fillVenue=()=>{const v=venueData.venues.find(x=>x.name===form.elements.venue.value);if(!v)return;form.elements.city.value=v.city;form.elements.zones.value=v.zones.map(z=>`${z.name},0,${z.capacity},${z.accessible||0},${z.rows||0},${z.seatsPerRow||8}`).join('\n')};form.elements.venue.onchange=fillVenue;if(!editing)fillVenue()}
      form.onsubmit=async ev=>{ev.preventDefault();const f=Object.fromEntries(new FormData(form)),blockedSeats=f.blockedSeats.split(',').map(s=>s.trim()).filter(Boolean),functions=f.functions.split(/\n/).map((line,i)=>{const [date,hour]=line.split(',').map(s=>s.trim());return{id:String(i+1),date,hour}}).filter(fn=>/^\d{4}-\d{2}-\d{2}$/.test(fn.date)&&/^\d{2}:\d{2}$/.test(fn.hour));if(!functions.length){$('#event-error').textContent='Agrega al menos una función con fecha y hora válidas.';return;}const zones=f.zones.split(/\n/).map(line=>{const [name,price,capacity,accessibleCount,rows,seatsPerRow]=line.split(',').map(x=>x.trim()),r=Number(rows)||0,c=Number(seatsPerRow)||8,general=/general/i.test(name),seats=general?[]:r?Array.from({length:r*c},(_,i)=>`${String.fromCharCode(65+Math.floor(i/c))}${i%c+1}`):Array.from({length:Math.min(Number(capacity),400)},(_,i)=>`${String.fromCharCode(65+Math.floor(i/8))}${i%8+1}`);return{name,price:Number(price),capacity:Number(capacity),type:general?'general':'seat',blockedSeats,seats,rows:r,seatsPerRow:c,accessible:general?[]:Array.from({length:Number(accessibleCount)||0},(_,i)=>seats[i]).filter(Boolean)}});try{const payload={...f,date:functions[0].date,hour:functions[0].hour,functions,zones,blockedSeats,ticketLimit:Number(f.ticketLimit),type:zones[0]?.type,class:'p1',tag:'EVENTO'};if(form.dataset.id)payload.id=form.dataset.id;await accountApi('events',payload);toast('Borrador guardado.');renderRolePanel({app,user,toast,eventName,sub,catalogEvents})}catch(e){$('#event-error').textContent=e.message}};
    }
    return;
  }
  if(user.role!=='administrador'){app.innerHTML='<section class="panel"><h1>Acceso denegado</h1></section>';return;}
  const tab=sub[0]||'general';
  if(tab!=='general'){app.innerHTML=`<div class="eyebrow">Administración</div><h1>Panel de control</h1>${adminTabs(tab)}<div id="admin-body"></div>`;await renderAdminTab({app,tab,toast,events:catalogEvents});return;}
  let [requests,events,venues,holds,unresolved]=await Promise.all([accountApi('admin/organizers',null,'GET'),accountApi('events',null,'GET'),accountApi('venues',null,'GET'),accountApi('admin/holds',null,'GET'),accountApi('admin/unresolved-payments',null,'GET')]);
  const holdCounts=holds.counts,expiredRows=holds.expired.map(h=>`<tr><td>${new Date(h.closed).toLocaleString('es-MX')}</td><td>${esc(h.email)}</td><td>${esc(eventName(h.eventId))} · ${esc(h.zone)}</td><td>${h.kind==='seat'?esc(h.seats.join(', ')):`${h.quantity} accesos`}</td><td>${esc(h.reason)}</td></tr>`).join('');
  const expiredSection=`<section class="panel" id="expired-holds"><h2>Compras expiradas</h2><p><strong class="stat">${holdCounts.expired}</strong> compras expiradas · ${holdCounts.active+holdCounts.paying} en curso · ${holdCounts.completed} pagadas · ${holdCounts.cancelled} canceladas</p>${expiredRows?`<div class="table-scroll"><table class="data-table"><thead><tr><th>Venció</th><th>Cuenta</th><th>Evento</th><th>Lugares</th><th>Motivo</th></tr></thead><tbody>${expiredRows}</tbody></table></div>`:'<p class="muted">Aún no hay compras expiradas.</p>'}</section>`;
  const orphanRows=(unresolved.payments||[]).map(p=>`<tr><td>${new Date(p.created).toLocaleString('es-MX')}</td><td>${esc(p.email)}</td><td><strong>$${Number(p.amount).toFixed(2)} MXN</strong></td><td>•••• ${esc(p.last4)} · ${esc(p.gateway_ref)}</td><td><span class="badge ${p.status==='resolved'?'':'warning'}">${p.status==='resolved'?'Resuelto':'Pendiente'}</span><br><small>${esc(p.reason)}</small></td><td>${p.status==='unresolved'?`<button class="btn secondary small resolve-payment" data-id="${esc(p.id)}">Resolver</button>`:`<small class="muted">${esc(p.resolution_notes||'Resuelto')}</small>`}</td></tr>`).join('');
  const orphanSection=`<section class="panel" id="unresolved-payments"><h2>Pagos sin boletos (RN-12)</h2><p>Cobros aprobados en pasarela que no generaron boletos para resolución manual o reembolso.</p>${orphanRows?`<div class="table-scroll"><table class="data-table"><thead><tr><th>Fecha</th><th>Cuenta</th><th>Monto</th><th>Detalle cobro</th><th>Motivo</th><th>Acción</th></tr></thead><tbody>${orphanRows}</tbody></table></div>`:'<p class="muted">No hay pagos pendientes de resolución.</p>'}</section>`;
  app.innerHTML=`<div class="eyebrow">Administración</div><h1>Panel de control</h1>${adminTabs('general')}<p id="role-error" class="error" role="alert"></p>${orphanSection}${expiredSection}<div class="split"><section class="panel"><h2>Solicitudes de organizador</h2>${requests.users.map(u=>`<article class="ticket"><div><strong>${esc(u.name)} · ${esc(u.email)}</strong><p>${esc(u.organizer_status)}</p>${u.organizer_status==='pending'?`<button class="btn small decide-organizer" data-id="${esc(u.id)}" data-approve="1">Aprobar</button> <button class="btn secondary small decide-organizer" data-id="${esc(u.id)}" data-approve="0">Rechazar</button>`:''}</div></article>`).join('')||'<p>No hay solicitudes pendientes.</p>'}</section><section class="panel"><h2>Alta de recinto</h2><form id="venue-form"><div class="field"><label>Nombre</label><input name="name" required></div><div class="field"><label>Ciudad</label><input name="city" required></div><div class="field"><label>Zonas (una por línea: nombre,capacidad,accesibles)</label><textarea name="zones" placeholder="Platea,120,4\nGeneral,300,0" required></textarea></div><button class="btn">Guardar recinto</button></form><h3>Recintos</h3>${venues.venues.map(v=>`<p><strong>${esc(v.name)}</strong> · ${esc(v.city)} · ${v.zones.length} zonas</p>`).join('')||'<p>Aún no hay recintos.</p>'}</section></div><section><h2>Eventos para revisión</h2><div class="cards">${events.events.filter(e=>e.status==='review'||e.status==='rejected'||e.status==='published').map(e=>`<article class="panel"><span class="badge">${esc(e.status)}</span><h3>${esc(e.name)}</h3><p>${esc(e.date||'')} · ${esc(e.venue||'')}</p>${e.status==='published'?`<a class="btn secondary small" href="#panel/evento/${encodeURIComponent(e.id)}">Ver panel</a>`:''}${e.status==='review'?`<label>Motivo si se rechaza <input class="reason" data-id="${esc(e.id)}"></label><button class="btn small decide-event" data-id="${esc(e.id)}" data-approve="1">Aprobar y publicar</button> <button class="btn secondary small decide-event" data-id="${esc(e.id)}" data-approve="0">Rechazar</button>`:''}</article>`).join('')||'<p>No hay eventos enviados a revisión.</p>'}</div></section>`;
  document.querySelectorAll('.resolve-payment').forEach(b=>b.onclick=async()=>{const notes=prompt('Indica la resolución del pago huérfano (ej. Reembolso emitido o Boletos asignados):','Reembolso emitido');if(!notes)return;try{await accountApi(`admin/unresolved-payments/${b.dataset.id}/resolve`,{notes},'POST');toast('Pago marcado como resuelto.');renderRolePanel({app,user,toast,eventName,sub,catalogEvents})}catch(e){showError(e)}});
  $('#venue-form [name="zones"]').placeholder='Platea,120,4,10,12\nGeneral,300,0,0,0';$('#venue-form [name="zones"]').previousElementSibling.textContent='Zonas (nombre, capacidad, accesibles, filas, asientos por fila)';
  document.querySelectorAll('.decide-organizer[data-approve="0"]').forEach(b=>b.insertAdjacentHTML('beforebegin',`<input class="organizer-reason" data-id="${esc(b.dataset.id)}" placeholder="Motivo del rechazo" aria-label="Motivo del rechazo"> `));
  document.querySelectorAll('.decide-organizer').forEach(b=>b.onclick=async()=>{const reason=document.querySelector(`.organizer-reason[data-id="${CSS.escape(b.dataset.id)}"]`)?.value||'';try{await accountApi('admin/organizers',{userId:b.dataset.id,approve:b.dataset.approve==='1',reason},'PUT');renderRolePanel({app,user,toast,eventName,sub,catalogEvents})}catch(e){showError(e)}});
  $('#venue-form').onsubmit=async ev=>{ev.preventDefault();const f=Object.fromEntries(new FormData(ev.target)),zones=f.zones.split(/\n/).map(line=>{const [name,capacity,accessible,rows,seatsPerRow]=line.split(',').map(x=>x.trim()),count=Number(capacity);return{name,capacity:count,accessible:Number(accessible)||0,rows:Number(rows)||0,seatsPerRow:Number(seatsPerRow)||0,type:/general/i.test(name)?'general':'seat',seats:/general/i.test(name)?[]:Array.from({length:count},(_,i)=>`${String.fromCharCode(65+Math.floor(i/(Number(seatsPerRow)||8)))}${i%(Number(seatsPerRow)||8)+1}`)}});try{await accountApi('venues',{name:f.name,city:f.city,zones});toast('Recinto guardado.');renderRolePanel({app,user,toast,eventName,sub,catalogEvents})}catch(e){showError(e)}};
  document.querySelectorAll('.decide-event').forEach(b=>b.onclick=async()=>{const reason=document.querySelector(`.reason[data-id="${CSS.escape(b.dataset.id)}"]`)?.value||'';if(b.dataset.approve==='0'&&!reason.trim()){showError(new Error('Escribe el motivo del rechazo.'));return}try{await accountApi(`events/${b.dataset.id}/decision`,{approve:b.dataset.approve==='1',reason});toast('Revisión guardada.');renderRolePanel({app,user,toast,eventName,sub,catalogEvents})}catch(e){showError(e)}});
}
